### PR TITLE
fix nil dereference

### LINKED ISSUE #6: Got segvault on notification
Hi,

I got a segmentation fault on line 43.

it seems the error handling has some problem :)

Version I use: v1.0.5

---
when creating a subscription to a server that previously has a session and subscriptions with another client.
but if the go-netconf client connect and create subscription first then the other client create session and subscriptions with the same server it will work fine.
I think the root cause for my case is I set the timeout too small.
But the error handling seems not process it well.

https://github.com/openshift-telco/go-netconf-client/blob/5c734946781abc558244653b8300c9b8df2fe3c7/netconf/operations.go#L41-L44

### PR DESCRIPTION
**Pull request by femiaf13-precisionOT**
Fixes #6

### CODE REVIEW

File: netconf/operations.go [hunk 1]
```diff
@@ -40,7 +40,9 @@ func (session *Session) CreateNotificationStream(
 	session.Listener.Register(message.NetconfNotificationStreamHandler, callback)
 	sub := message.NewCreateSubscription(stopTime, startTime, stream)
 	rpc, err := session.SyncRPC(sub, timeout)
-	if err != nil || len(rpc.Errors) != 0 {
+	if rpc == nil {
+		return fmt.Errorf("fail to create notification stream with errors. Error: %w", err)
+	} else if err != nil || len(rpc.Errors) != 0 {
 		return fmt.Errorf("fail to create notification stream with errors: %s. Error: %w", rpc.Errors, err)
```
Comment (adetalhouet) [inline netconf/operations.go:46]: do you mind restructuring the if statement as follow?
```
	if err != nil {
		errMsg := "fail to create notification stream"
		if rpc != nil && len(rpc.Errors) != 0 {
			errMsg += fmt.Sprintf(" with errors: %s", rpc.Errors) 
		}
		return fmt.Errorf("%s: %w", errMsg, err)
	}
```

**Review by adetalhouet — CHANGES_REQUESTED** [review]
Thank you for the fix. Do you mind addressing the comment? Thanks

File: netconf/operations.go (hunk 1 above)
Comment (femiaf13-precisionOT) [reply netconf/operations.go]: Done! Thanks for the suggestion, it's cleaner to read
